security.jwt.secret=123456789123456789123456789123456789
spring.application.name=Bank_Management_System
spring.datasource.url=jdbc:mysql://localhost:3306/bank_management_rest
spring.datasource.username=root
spring.datasource.password=Dhyey1212
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
springdoc.api-docs.path=/v3/api-docs
# Ensure Swagger UI uses absolute docs URL instead of relative under /swagger-ui
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.urls[0].name=Bank Management API
springdoc.swagger-ui.urls[0].url=/v3/api-docs
springdoc.swagger-ui.use-root-path=true
